"use client";

import { useState, useEffect, useCallback } from "react";
import {
  requestCertificate,
  getCertificateOrder,
  type AcmeOrderStatus,
} from "@/lib/api";

function downloadFile(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function CopyButton({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);

  return (
    <button
      onClick={handleCopy}
      className="rounded bg-[#222] px-2 py-0.5 text-[0.7rem] text-[#666] transition-colors hover:text-[#e0e0e0]"
    >
      {copied ? "Copied!" : label}
    </button>
  );
}

interface CertRequestProps {
  domain: string;
  disabled: boolean;
}

export function CertRequest({ domain, disabled }: CertRequestProps) {
  const [orderId, setOrderId] = useState<string | null>(null);
  const [orderStatus, setOrderStatus] = useState<AcmeOrderStatus | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showKey, setShowKey] = useState(false);

  // Polling
  useEffect(() => {
    if (!orderId) return;
    if (
      orderStatus?.status === "issued" ||
      orderStatus?.status === "failed"
    )
      return;

    const interval = setInterval(async () => {
      try {
        const order = await getCertificateOrder(orderId);
        setOrderStatus(order);
      } catch {
        // Keep polling on transient errors
      }
    }, 3000);

    return () => clearInterval(interval);
  }, [orderId, orderStatus?.status]);

  const handleRequest = useCallback(async () => {
    if (disabled || loading) return;
    setLoading(true);
    setError(null);
    setOrderStatus(null);
    setOrderId(null);
    setShowKey(false);

    try {
      const res = await requestCertificate(domain);
      setOrderId(res.order_id);
      setOrderStatus({
        order_id: res.order_id,
        status: res.status as AcmeOrderStatus["status"],
        domain,
        certificate_pem: null,
        private_key_pem: null,
        error: null,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Request failed";
      setError(msg);
    }
    setLoading(false);
  }, [domain, disabled, loading]);

  const status = orderStatus?.status;

  return (
    <div className="mt-6">
      {/* Divider */}
      <div className="mb-6 border-t border-[#222]" />

      <div className="rounded-[10px] border border-[#222] bg-[#141414] p-5">
        <h3 className="mb-3 text-lg font-semibold">HTTPS Certificate</h3>

        {/* Request button */}
        {!orderId && !error && (
          <>
            <button
              onClick={handleRequest}
              disabled={disabled || loading}
              className="rounded-lg bg-[#222] px-4 py-2.5 text-sm font-semibold text-[#e0e0e0] transition-colors hover:bg-[#333] disabled:cursor-not-allowed disabled:opacity-50"
            >
              {loading ? "Requesting..." : "Get HTTPS Certificate"}
            </button>
            <p className="mt-2 text-xs text-[#666]">
              🔒 Your private key is generated by the bot and returned to you.
              The bot does not retain it after delivery.
            </p>
            {disabled && (
              <p className="mt-1 text-xs text-[#666]">
                Publish at least one DNS record first.
              </p>
            )}
          </>
        )}

        {/* Error — ACME disabled or other */}
        {error && (
          <div className="space-y-3">
            <div className="rounded-lg border border-[rgba(231,76,60,0.25)] bg-[rgba(231,76,60,0.08)] px-4 py-3 text-sm text-[#e74c3c]">
              ❌ {error}
            </div>
            <button
              onClick={() => {
                setError(null);
                setOrderId(null);
                setOrderStatus(null);
              }}
              className="rounded-lg bg-[#222] px-3 py-2 text-xs font-semibold text-[#e0e0e0] hover:bg-[#333]"
            >
              Try Again
            </button>
          </div>
        )}

        {/* Pending / In-progress states */}
        {orderStatus && (status === "pending" || status === "challenge_published" || status === "verifying") && (
          <div className="space-y-3">
            <div className="flex items-center gap-3 rounded-lg border border-[#222] bg-[#0a0a0a] px-4 py-3">
              {status === "pending" && (
                <>
                  <span className="inline-block h-3 w-3 animate-pulse rounded-full bg-[#ff6b35]" />
                  <span className="text-sm text-[#ff6b35]">
                    Creating certificate order...
                  </span>
                </>
              )}
              {status === "challenge_published" && (
                <>
                  <span className="inline-block h-3 w-3 animate-pulse rounded-full bg-[#ff6b35]" />
                  <span className="text-sm text-[#ff6b35]">
                    DNS challenge published, waiting for verification
                    <span className="animate-pulse">...</span>
                  </span>
                </>
              )}
              {status === "verifying" && (
                <>
                  <span className="inline-block h-3 w-3 animate-pulse rounded-full bg-[#ff6b35]" />
                  <span className="text-sm text-[#ff6b35]">
                    Let&apos;s Encrypt is verifying your domain...
                  </span>
                </>
              )}
            </div>
            <p className="text-xs text-[#666]">
              Domain: <code className="text-[#bbb]">{orderStatus.domain}</code>
            </p>
          </div>
        )}

        {/* Issued */}
        {orderStatus && status === "issued" && (
          <div className="space-y-4">
            <div className="rounded-lg border border-[rgba(46,204,113,0.25)] bg-[rgba(46,204,113,0.08)] px-4 py-3 text-center">
              <p className="text-sm font-semibold text-[#2ecc71]">
                ✅ Certificate ready!
              </p>
              <p className="mt-1 text-xs text-[#666]">
                Certificate valid for 90 days
              </p>
            </div>

            {/* Certificate */}
            {orderStatus.certificate_pem && (
              <div className="rounded-lg border border-[#222] bg-[#0a0a0a] p-3">
                <div className="mb-2 flex items-center justify-between">
                  <div className="text-[0.7rem] uppercase tracking-wider text-[#666]">
                    Certificate
                  </div>
                  <div className="flex gap-1">
                    <CopyButton
                      text={orderStatus.certificate_pem}
                      label="Copy"
                    />
                    <button
                      onClick={() =>
                        downloadFile(
                          orderStatus.certificate_pem!,
                          `${orderStatus.domain}.pem`,
                        )
                      }
                      className="rounded bg-[#222] px-2 py-0.5 text-[0.7rem] text-[#666] transition-colors hover:text-[#e0e0e0]"
                    >
                      Download
                    </button>
                  </div>
                </div>
                <pre className="max-h-[120px] overflow-y-auto break-all font-mono text-xs text-[#bbb]">
                  {orderStatus.certificate_pem.slice(0, 200)}
                  ...
                </pre>
              </div>
            )}

            {/* Private Key */}
            {orderStatus.private_key_pem && (
              <div className="rounded-lg border border-[rgba(231,76,60,0.15)] bg-[#0a0a0a] p-3">
                <div className="mb-2 flex items-center justify-between">
                  <div className="text-[0.7rem] uppercase tracking-wider text-[#666]">
                    Private Key
                  </div>
                  <div className="flex gap-1">
                    <CopyButton
                      text={orderStatus.private_key_pem}
                      label="Copy"
                    />
                    <button
                      onClick={() =>
                        downloadFile(
                          orderStatus.private_key_pem!,
                          `${orderStatus.domain}-key.pem`,
                        )
                      }
                      className="rounded bg-[#222] px-2 py-0.5 text-[0.7rem] text-[#666] transition-colors hover:text-[#e0e0e0]"
                    >
                      Download
                    </button>
                  </div>
                </div>
                {showKey ? (
                  <pre className="max-h-[120px] overflow-y-auto break-all font-mono text-xs text-[#bbb]">
                    {orderStatus.private_key_pem.slice(0, 200)}
                    ...
                  </pre>
                ) : (
                  <button
                    onClick={() => setShowKey(true)}
                    className="text-xs text-[#ff6b35] hover:underline"
                  >
                    Click to reveal private key
                  </button>
                )}
              </div>
            )}

            <div className="rounded-lg border border-[rgba(231,76,60,0.15)] bg-[rgba(231,76,60,0.05)] px-4 py-3 text-xs text-[#e8a49c]">
              Install these on your web server. The private key is secret —
              never share it publicly.
            </div>
          </div>
        )}

        {/* Failed */}
        {orderStatus && status === "failed" && (
          <div className="space-y-3">
            <div className="rounded-lg border border-[rgba(231,76,60,0.25)] bg-[rgba(231,76,60,0.08)] px-4 py-3 text-sm text-[#e74c3c]">
              ❌ Certificate failed: {orderStatus.error || "Unknown error"}
            </div>
            <button
              onClick={() => {
                setError(null);
                setOrderId(null);
                setOrderStatus(null);
                setShowKey(false);
              }}
              className="rounded-lg bg-[#222] px-3 py-2 text-xs font-semibold text-[#e0e0e0] hover:bg-[#333]"
            >
              Try Again
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
